### ISSUE TITLE
Example "CRing-AllInOne.tex" is missing a file

### ISSUE THREAD

**Issue by Dirk-** [ktraunmueller/Compositor#119]
When I open `CRing-AllInOne.tex`, I get a file-not-found error for `ntheorem.sty`. The outline of the document is shown, but not the document itself.

**Comment by ktraunmueller** [comment]
The `.sty` extension means it's a missing package - please refer to [this blog post](http://compositorapp.com/blog/2017-07-08/InstallingPackagesAndFonts/) for instructions on how to install additional packages in the preview version.
