### ISSUE TITLE
Linux version of Compositor?

### ISSUE THREAD

**Issue by NikoKrause** [ktraunmueller/Compositor#165]
Hey,

since I read an article about Compositor I think it's the most exciting LaTeX news in years.
I know it's in a really early stage, but are there any plans on porting this some day to Linux?

Regards

NikoKrause

**Comment by ktraunmueller** [comment]
Hi Niko,

no, I don't think that will ever happen. Also not planning a Windows version, for that matter. But I do consider an iPad version of the app.

**Comment by NikoKrause** [comment]
Why?

**Comment by ktraunmueller** [comment]
As a one-man show, I can only support one platform, and my platform of choice is the Mac.

**Comment by NikoKrause** [comment]
Use a cross-platform programming language
