### ISSUE TITLE
Book Template: Deleting second author placeholder causes a crash

### ISSUE THREAD

**Issue by McPringle** [ktraunmueller/Compositor#229]
I started a new document with the book template, successfully replaced the title placeholder and tried to modify the author placeholder. Then this message occured:

```
LaTeX Error: Command \\end unavailable in encoding T1. (around line 16)
```

I closed and reopened the document and got the same error. The relevant part of the code is:

```tex
\begin{document}

\title{A Simple Book}

\author{
First Autho
\a}

\maketitle

\tableofcontents
```

The `\a` looks like a leftover of the second author placeholder, which I deleted because this book has only one author. I manually removed the `\a` with TextMate and then I was able to continue with Compositor.

**Comment by ktraunmueller** [comment]
Awesome bug report, thanks a lot!

**Comment by ktraunmueller** [comment]
Thanks for the excellent bug report!

**Comment by ktraunmueller** [comment]
No longer crashes in 1.3. 

Deleting the second author results in the following source (fragment):
```
\author{
First Author
\and
}
```
The remaining `\and` can then be removed using the "Author(s)" picker in the Document inspector panel:

<img width="271" alt="screen shot 2018-06-14 at 23 53 48" src="https://user-images.githubusercontent.com/650763/41440269-3578fac4-702e-11e8-898d-6ce286bc60e2.png">

Closing.
