### ISSUE TITLE
Wrong (?) positioning of insertion point in formula editor

### ISSUE THREAD

**Issue by Dirk-** [ktraunmueller/Compositor#537]
When I type a new formula (starts with default x) and move the insertion point to the right of x, the insertion point moves to the left of the first new character inserted. So if I want to type x123, it goes x231.

Same behavior every time after I move the cursor in a formula.

macOS 10.15.7, Compositor 1.15.0, system language German 

Is that intended behavior?

**Comment by ktraunmueller** [comment]
Fixed in 1.16, thanks for reporting @Dirk-!
