### ISSUE TITLE
No release notes in Sparkle update window

### ISSUE THREAD

**Issue by Dirk-** [ktraunmueller/Compositor#548]
The update dialog of version 1.17 does not show any release notes:

<img width="620" alt="Bildschirmfoto 2021-04-09 um 11 33 56" src="https://user-images.githubusercontent.com/7225580/114161391-488eed00-9928-11eb-97f0-72d95343bec0.png">

**Comment by ktraunmueller** [comment]
@Dirk- Is this on Big Sur?

**Comment by Dirk-** [comment]
Yes, macOS 11.2.3

**Comment by ktraunmueller** [comment]
I think this is probably caused by `http://` URLs in the Sparkle appcast -- I forgot to change these to `https://`.

**Comment by ktraunmueller** [comment]
Should be fixed in 1.18
