### ISSUE TITLE
Can't open the application

### ISSUE THREAD

**Issue by HiramTheHero** [ktraunmueller/Compositor#554]
Hello.

I can install Compositor like normal from this link https://compositorapp.com/ .
After I move Compositor to the Application folder and when I open the application I get a window with the finder icon that states "The application "Compositor" can't be opened." I also get a window that states "Compositor quit unexpectedly" and offers me to send a report to Apple.

System information:
Macbook Pro M1 Chip
MacOS Version: 12.1

Please let me know if there is anymore information you need from me.

**Comment by ravivmg** [comment]
Same here:

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by ktraunmueller** [comment]
I updated the developer certificate and created a new build that should run again: https://github.com/ktraunmueller/Compositor/releases/tag/1.18.0
