### ISSUE TITLE
Provide a UTF-8 compatible workflow

### ISSUE THREAD

**Issue by ktraunmueller** [ktraunmueller/Compositor#90]
Make the editor accept non-ASCII* text input, and provide a UTF-8 compatible workflow.

*) more precisely, accented Latin characters

**Comment by spruce** [comment]
Do you plan to support inputenc? While working with others on latex documents in german it would be nice if that would be possible

**Comment by ktraunmueller** [comment]
`inputenc` will not be supported directly, since it is incompatible with a core assumption behind the source-to-DVI mapping mechanism required for WYSIWYG editing.

I am aware, however, that a lot of people are currently using `inputenc`. For these users, I created this issue (make the editor accept diacritics), and https://github.com/ktraunmueller/Compositor/issues/99 (provide a smooth migration path).

**Comment by ktraunmueller** [comment]
Struggling a bit with a concise yet understandable description what this ticket is actually about. 

There seems to be a lot of confusion about `\usepackage[utf8]{inputenc}`, file encodings, BOM's (see e.g., [this discussion](https://tex.stackexchange.com/questions/370278/is-there-any-reason-to-use-inputenc)). I will try to clarify the details in the 1.3 release post on the blog.

Short version: Compositor 1.3 will
- require `\usepackage[utf8]{inputenc}`
- require UTF-8 file encoding

**Comment by ktraunmueller** [comment]
**Implemented** in 1.3
